config/routes.rb
Som::Application.routes.draw do
  
  devise_for :users

  root :to => 'static_pages#home'
  
  resources :results 
  
  resources :runs do
    resources :results  
  end

end

app/models/factor.rb
class Factor < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :results, :dependent => :destroy
end

app/models/result.rb
require 'net/http'

class Result < ActiveRecord::Base
   attr_accessible :name, :url, :run_id, :factor_id

   belongs_to :run
   belongs_to :factor

  def imgS3Path
    s3Path = self.url.split('/')[-2] + '/' + self.url.split('/')[-1]
    s3Path
  end


end

app/models/run.rb
class Run < ActiveRecord::Base
  attr_accessible :title, :path, :s3folder

  has_many :results, :dependent => :destroy

  after_create :create_results

  def getS3Objs
    if Rails.env.development?
      s3 = AWS::S3.new(
        #:access_key_id => S3_CONFIG[::Rails.env]["access_key_id"],
        #:secret_access_key => S3_CONFIG[::Rails.env]["secret_access_key"] 
        :access_key_id     => ENV['S3_KEY'],
        :secret_access_key => ENV['S3_SECRET']               
      )
    elsif Rails.env.production?
      s3 = AWS::S3.new(
        :access_key_id     => ENV['S3_KEY'],
        :secret_access_key => ENV['S3_SECRET']     
      )
    end
    objs = []
    #debugger  
    s3.buckets['somrst'].objects.with_prefix(self.s3folder.to_s + '/').each do |object|
      objs.push object.key
    end


    return objs
  end

  private

  def create_results
    Factor.all.each do |factor|
      self.results.create(factor_id: factor.id, name: factor.description, url: self.path.to_s + factor.name + ".png")
    end  
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
    before_filter :authenticate_user!
    
    def index
      @results_all = Result.find_all_by_run_id(params[:run_id])
      @results = []
      @s3Objs = Run.find(params[:run_id]).getS3Objs
      @results_all.each do |result|
        @results.push result if @s3Objs.map(&:downcase).include? result.imgS3Path.downcase
      end

      @run = Run.find(params[:run_id])
    end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
    before_filter :authenticate_user!

    def index
      @runs = Run.all
    end
    
    def new
      @run = Run.new
    end

    def create
      @run = Run.new(title: params[:run][:title],
                     s3folder: params[:run][:s3folder])                                             
        # note update_attributes Updates this resource with all the attributes 
        # from the passed-in Hash and requests that the record be saved.
      
      @run.path = "https://s3-us-west-2.amazonaws.com/somrst/" + @run.s3folder + "/"
      if @run.save
        flash[:success] = "Run created!"
        redirect_to run_results_path(@run)
      else
        render :new 
      end
    end

    def destroy
      @run = Run.find(params[:id])
      @run.destroy

    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/layouts/application.html.haml
!!! 5
- env = Rails.application.assets.is_a?(Sprockets::Index) ? Rails.application.assets.instance_variable_get('@environment') : Rails.application.assets
%html
  %head
    %title Som
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = yield :javascript_includes
    = csrf_meta_tags
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  %body
    .wrapper
      %header.navbar.navbar-inverse.navbar-fixed-top
        .navbar-inner
          #header.collapse.in.container
            .row
              #logo.span2
                %a{:href => root_path}
              .span7      
                %nav
                  %ul.nav.pull-right                    
                    %li= link_to "Home", root_path  
                    - if user_signed_in?               
                      %li
                        .btn-group
                          = link_to "Runs", runs_path, class: "btn btn-info"
                      %li
                        = link_to current_user.email, edit_user_registration_path                       
                      %li
                        = link_to "Logout", destroy_user_session_path, { method: :delete, id: "sign_out" }                    
                    - else               
                      %li
                        = link_to "Sign up", new_user_registration_path
                      %li
                        = link_to "Login", new_user_session_path
              #branding.span3
                %nav
                  %ul.nav.bannerText2
                    %li= link_to "RST development", root_path 
      .container
        - flash.each do |key, value|
          = content_tag(:div, value, class: "alert alert-#{key}")      
        = yield

app/views/results/_result.html.haml
%li.span3.list-group-item.result_item
  %a{ href: result_path(result.id)}
    %div.list-group-item-heading.center= result.name
    = image_tag(result.url, :class => "img-responsive")

app/views/results/index.html.haml
.span8
%h3
  = 'Results from ASW S3 folder: ' + @run.s3folder.to_s
.row
  %ul
    %li
      = link_to 'back to runs list', runs_path
    %li
      = "Run description: " + @run.title   
- if @results.any?
  %ul.results_items.list-group
    = render @results

app/views/runs/_run.html.haml
%li
  = link_to run.title, run_results_path(run.id)

app/views/runs/_run_form.html.haml
%p.row.span8
  %h2.span4 First create a folder on S3 and add the plots that you want to share
%p.row.span8 
= form_for(run, :url => runs_url(@run)) do |f|
  = render partial: 'shared/error_messages', locals: {object: f.object}
  .field                                             
    %p.row.span8.spacer30  
    %p.row.span8
      .span1
        = f.label :title, "Title"
      .span6  
        = f.text_field :title
    %p.row.span8.spacer30
    %p.row.span8
      .span1
        = f.label :s3folder, "S3 Folder Name"
      .span6  
        = f.text_field :s3folder 
    %p.row.span8.spacer30                  
    %p.row.span8  
      = f.submit "Save run", class: "btn btn-large btn-primary"

app/views/runs/index.html.haml

.row
  \#{link_to "New Run", new_run_path, class: "btn btn-primary btn-lg"}
.row
  %h3.span8 SOM runs
.row  
  - if @runs.any?
    %ul.span8.runs
      = render @runs

app/views/runs/new.html.haml
.row
  .span8.offset2
    = render partial: 'run_form', locals: {run: @run}

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          * #{msg}

app/views/static_pages/home.html.haml
- if user_signed_in?
  .row
    %h3.well.well-small 
      =link_to 'View the results', runs_path    
    .spacer200      
- else
  .row.center.hero-unit
    .row
      %h2 Self Organising Map (SOM) results
      %h2.span2.offset5
        \#{link_to "Login",  new_user_session_path, class: "btn btn-primary btn-lg btn-block"}
      .spacer50
    .row  
      %Span
        no account?  
      \#{link_to "Sign up here", new_user_registration_path}                
  .row.home-img 
    .span4
      =image_tag("https://s3-us-west-2.amazonaws.com/somrst/run1/clusters.png")
    .span4
      =image_tag("https://s3-us-west-2.amazonaws.com/somrst/run1/zq.png")
    .span4
      =image_tag("https://s3-us-west-2.amazonaws.com/somrst/run1/age.png")